name: Build tools
on:
  push:
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.19'
      id: go
    - name: Install deps
      run: sudo apt install -y python3 pandoc
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Pull tag
      run: git fetch --tags
    - name: Build doc
      run: |
        python3 assemble_md.py ./docs --exclude ./docs/vendor ./docs/.bundle ./docs/.jekyll-cache ./docs/_site  > MANUAL.md
        pandoc MANUAL.md -s -t man -o trusted-cgi.1
        pandoc --metadata title="Trusted-CGI manual" MANUAL.md -s --include-in-header=./docs/assets/github-pandoc.css --toc -o MANUAL.html
        gzip trusted-cgi.1
    - uses: azure/docker-login@v1
      with:
        username: 'reddec'
        password: ${{ secrets.DOCKERIO_PASSWORD }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --release-footer _footer.md --release-header release-note.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}