name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [Dockerfile, Dockerfile.minimal]
        include:
          - target: Dockerfile
            platform: linux/amd64,linux/arm64,linux/arm/v7
            tag: latest
          - target: Dockerfile.minimal
            platform: linux/amd64
            tag: minimal
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.19'
      id: go
    - name: Install deps
      run: sudo apt install -y python3 pandoc
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Pull tag
      run: git fetch --tags
    - name: Build doc
      run: |
        python3 assemble_md.py ./docs --exclude ./docs/vendor ./docs/.bundle ./docs/.jekyll-cache ./docs/_site  > MANUAL.md
        pandoc MANUAL.md -s -t man -o trusted-cgi.1
        pandoc --metadata title="Trusted-CGI manual" MANUAL.md -s --include-in-header=./docs/assets/github-pandoc.css --toc -o MANUAL.html
        gzip trusted-cgi.1
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Run GoReleaser for Server
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --rm-dist --snapshot --id server --single-target -o ./cgi-ctl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run GoReleaser for Client
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --rm-dist --snapshot --id client --single-target -o ./trusted-cgi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ${{ matrix.target }}
        context: .
        target: actions
        push: true
        tags: ghcr.io/${{ github.actor }}/trusted-cgi:${{ matrix.tag }}
        platforms: ${{ matrix.platform }}
