name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        fetch-depth: 0
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Pull tag
      run: git fetch --tags
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/trusted-cgi:latest
        platforms: linux/amd64,linux/arm64,linux/arm
  build-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        fetch-depth: 0
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Pull tag
      run: git fetch --tags
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile.minimal
        push: true
        tags: ghcr.io/${{ github.actor }}/trusted-cgi:minimal
        platforms: linux/amd64,linux/arm64,linux/arm