name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [Dockerfile, Dockerfile.minimal]
        include:
          - target: Dockerfile
            platform: linux/amd64,linux/arm64,linux/arm/v7
            tag: latest
          - target: Dockerfile.minimal
            platform: linux/amd64
            tag: minimal
    steps:
    - name: Prepare git
      run: |
        git config --global --add safe.directory $(realpath .)
    - uses: actions/checkout@v3
      with:
        lfs: true
        fetch-depth: 0
        submodules: recursive
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Pull tag
      run: git fetch --tags
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y --no-install-recommends qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ${{ matrix.target }}
        push: true
        tags: ghcr.io/${{ github.actor }}/trusted-cgi:${{ matrix.tag }}
        platforms: ${{ matrix.platform }}
    - name: Debug with tmate on failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3